apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvpn-client.fullname" . }}
  labels:
    {{- include "openvpn-client.labels" . | nindent 4 }}
data:
{{- range .Values.config }}
{{- range $key, $value := .data }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
